### PR TITLE
Update julien-terrier.md

### PR DESCRIPTION
**Pull request by fisch192**
# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have checked my pool's registration status using https://pool.vet and have passed all checks.
- [ ] I have create an <IDENTITY_ID>.md for every stake pool operator of my pool file inside https://github.com/armada-alliance/armada-alliance/tree/main/services/website/content/en/stake-pools
- [ ] I have create a <POOL_ID>.md file for my pool inside https://github.com/armada-alliance/armada-alliance/tree/main/services/website/content/en/identities
- [ ] I have included my pool's ID in my <POOL_TICKER>.json file
- [ ] I have included my personal telegram handle in my <IDENTITY_ID>.md file

### CODE REVIEW

**Comment by AstroWa3l** [comment]
I am confused, you have two different pictures. Your profile picture does not look like the picture you have in the bio you made...

**Review by AstroWa3l — COMMENTED** [review]
so it seems you have two different pictures..Your profile pic looks different from the one on this identity page, I am not sure if pictures are supported yet as well.

**Comment by sublayerio** [comment]
@fisch192 bump

**Comment by sublayerio** [comment]
@fisch192 You seem to have edited an identity that belongs to Julien Terrier of MINI1 pool. Closing this PR.

**Pull request closed without merging**
