### PR TITLE
Adding [HAPPY] ❤ Happy Raspberry Pool :-)

### PR DESCRIPTION
**Pull request by kolesarp1**
Hi,
I would like to become member of Armada Alliance :-)
Your amazing documentation and alpine rpi os project helped me get started.

I'm successfully running 2 Raspberry Pi's 4, 16 GB, at my home.

Thank you so much.

Signed-off-by: Patrik <kolesarp1@gmail.com>

### CODE REVIEW

**Comment by AstroWa3l** [comment]
Hi, we have some issues with the website currently and the main developer is not reachable at the moment to fix it. I will let you know as soon as it is fixed.

**Comment by kolesarp1** [comment]
Sure, no worries :-)
Will wait. Thanks :+1:

**Comment by kolesarp1** [comment]
Hi, do you have any update on website fix by any chance? :-)
Thanks so much.
Patrik

**Comment by AstroWa3l** [comment]
@sublayerio and I are hoping to to fix it as soon as we are caught up with work. Maybe this week if we are lucky. Sorry for the delay.

**Comment by AstroWa3l** [comment]
Sorry for the delay but things are backup and running and thank you for being so patient :)

**Pull request merged**
