### PR TITLE
Create RUBY.json

### PR DESCRIPTION
**Pull request by mohammadsaadraza**
# Checklist:

- [ Done] My code follows the style guidelines of this project
- [Done ] I have performed a self-review of my own code
- [Done ] I have included my pool's ticker in my <POOL_TICKER>.json file
- [Done ] I have included my pool's ID in my <POOL_TICKER>.json file
- [ NO] I have included my personal telegram handle in my <POOL_TICKER>.json file
- [ DONE] I have checked my pool's registration status using https://pool.vet and have passed all checks.

### CODE REVIEW

**Review by AstroWa3l — APPROVED** [review]
Welcome to the Armada alliance :)

**Comment by mohammadsaadraza** [comment]
How do i get the logo on the site as well?

**Comment by AstroWa3l** [comment]
Hi, do you have a logo showing up on adapools.org? Also, please join the telegram if you have more questions. https://t.me/armada_alli 😀

**Comment by AstroWa3l** [comment]
It needs to be defined in the extended_metadata https://pool.vet/#Ruby 

Your pool has no extended metadata file. I would looking into the adapools.org example. 

https://a.adapools.org/extended-example

**Pull request merged**
