### PR TITLE
Pool upload

### PR DESCRIPTION
**Pull request by arnonmstyh**
# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have checked my pool's registration status using https://pool.vet and have passed all checks.
- [ ] I have create an <IDENTITY_ID>.md for every stake pool operator of my pool file inside https://github.com/armada-alliance/armada-alliance/tree/main/services/website/content/en/stake-pools
- [ ] I have create a <POOL_ID>.md file for my pool inside https://github.com/armada-alliance/armada-alliance/tree/main/services/website/content/en/identities
- [ ] I have included my pool's ID in my <POOL_TICKER>.json file
- [ ] I have included my personal telegram handle in my <IDENTITY_ID>.md file

### CODE REVIEW

**Comment by AstroWa3l** [comment]
Do you use a Arm cpu for your relay node? Block producer? both? Or None?

**Comment by sublayerio** [comment]
I spoke with him. He is intending on setting up a relay on a raspberry pi first. In the meantime we can accept his identity. The pool has to wait until he is running on arm.

**Comment by AstroWa3l** [comment]
Okay, thanks for clarifying @sublayerio

**Comment by sublayerio** [comment]
@arnonmstyh You can let us know once you have set up the relay. But we probably will know by following the general chat. Great that you've already added the files, looking great! 🚀

**Comment by sublayerio** [comment]
@AstroWa3l Np, we'll keep it open for a while. No rush.

**Comment by arnonmstyh** [comment]
I will let you guy know asap when it s online
Now im on setting up testnet node to raspberry pi
Thanks you so much

**Pull request closed without merging**
