### PR TITLE
Update 1e5f4eebc56a6726fd36af2f870b3bd62b204f3cd1b36e32e8a56737.md

### PR DESCRIPTION
**Pull request by tokenstakepool**
Added image url from poolpm (Cardano token registry)

### CODE REVIEW

**Review by AstroWa3l — APPROVED** [review]
we have a "content section" set up so I just added that part and added your link to the image file.

**Comment by tokenstakepool** [comment]
Hi @AstroWa3l, I was trying to restore the visualization of the stake pool logo, which appears on the site and map.

It was fine for months, but then it broke. I tried adding it to the .md file but it just shows the image on the bottom.
https://armada-alliance.com/stake-pools/1e5f4eebc56a6726fd36af2f870b3bd62b204f3cd1b36e32e8a56737

How can I remove this image and set it as logo in the map?

Thank you, and sorry for the inconvenience.

**Comment by AstroWa3l** [comment]
Yeah, well the image/logo is pulled via your pools extended metadata file

**Comment by AstroWa3l** [comment]
@tokenstakepool yeah, something is up with the URL you have in the metadata file. 
https://raw.githubusercontent.com/tokenstakepool/metadata/main/extPoolMetaData.json

I would try to fix the link and make sure it resolves to your image/logo because right now it leads to a pool.pm page. What some of us do is host our pool's metadata in our pool website repo. 

You can check my pool's metadata here and if you go to the link for our logo it shows the image.

https://github.com/piada-stakepool/website/blob/main/static/piada.extended-metadata.json

**Pull request merged**
