### PR TITLE
Add initial identity page for ASTOR

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Review by AstroWa3l — APPROVED** [review]
Great thanks!!!

**Comment by tdiesler** [comment]
Thanks for merging. I'm still stuck with Rule#3 the Telegram handle. IMHO, it is unreasonable to require the use of a specific messenger service that also forces me to publish my mobile phone number to the world. I also don't understand the Telegram business model, which makes it likely that they earn their money in ways that I might not agree with. I'm sorry, Telegram is unfortunately/currently not an option for me.

If the objective is, that the SPO can be reached by delegators - that is already possible through email, twitter, discord. Do you think we can find an alternative solution to get the #3 checkmark green?

I'm already taking to a second Pi4 hosting provider, so that I can tick "at least 2 relays" & "fully armed" in different locations.

cheers
-- thomas

**Comment by AstroWa3l** [comment]
Hi Thomas, I understand the pain of it but the main point is to be able to speak with other SPOs, I do not share my mobile number in telegram. We can maybe add a discord option as well that can satisfy the rule since I can still speak with you there and so can other members. 

Glad you are getting a second pi4 node up and running, the reason for this rule is because IOG recommends it and I think remember being a requirement to be eligible for Cardano Foundation delegation.

**Comment by tdiesler** [comment]
Yes, a discord option would be great - thanks

**Comment by sublayerio** [comment]
We use Telegram for two reasons:
- Monitoring the activity of each member, something we can't do manually given the amount of members that are joining
- Have a single place to contact stake pool operators.

My personal opinions on not adding Discord:
- It's for deeper conversations on a wide range of topics.
- More features don't make the Armada Alliance easier to understand or to maintain.

 Feel free to raise an issue (https://github.com/armada-alliance/armada-alliance/issues/new) and collect the majority of votes to get this changed.

**Pull request merged**
