### PR TITLE
Create Blockchain_AI.md

### PR DESCRIPTION
**Pull request by pgwadapool**
Sublayerio and I had a discussion to see if I can create a summary of the videos I am creating.  This is just a trial version.

### CODE REVIEW

**Comment by AstroWa3l** [comment]
Personally, I think this should be in blogs category. But I will just do whatever Sub and you said to do.

**Comment by pgwadapool** [comment]
Yes. Let me work with Sublayerio

**Comment by AstroWa3l** [comment]
well we are the same.

**Comment by AstroWa3l** [comment]
I am putting it in the blogs.

**Comment by AstroWa3l** [comment]
Lol

**Pull request merged**
